### ISSUE TITLE
No way to perform hitTest on Hexagon

### ISSUE THREAD

**Issue by jagger23** [orlikraf/flutter-hexagon#14]
Seems like the hitTest method is not available on Hexagon object but it is on CustomPainter so it should be possible to determine if a given x,y would match.

**Comment by orlikraf** [comment]
I don't understand what do you want to achieve. Are trying to detects taps on single hex?

**Comment by jagger23** [comment]
I am doing flutter web.

I want to highlight the hex when someone moves the mouse over it.

A hit test would be a simple way to find out which hex it is over.

**Comment by orlikraf** [comment]
Have you thought about having the child you put into the hexagon being responsible of detecting the hover gesture? 
The `MouseRegion` widget should be useful for this. Hopefully the hexagon should clip the detection zone to its shape so you won't get false calls outside it. But it have to be confirmed. I did noticed that `InkWell` highlight isn't clipping at all.

**Comment by jagger23** [comment]
No I didn’t think to try that. I will see if that will work for me.

Thanks
