### ISSUE TITLE
Does not support Sound Null Safety in Flutter 3.7.0+

### ISSUE THREAD

**Issue by laksh29** [orlikraf/flutter-hexagon#21]
![Screenshot_select-area_20230206003856](https://user-images.githubusercontent.com/81346526/216839754-55037209-d348-44ef-bf29-4ee0902e6d39.png)

The package does not support Sound Null Safety. And in the latest release of Flutter (Flutter 3.7.0) Sound Null Safety is mandatory to run a Flutter project

**Comment by orlikraf** [comment]
stable release 0.2.0 is updated with null safety
